### ISSUE TITLE
Apply to other imaging tools

### ISSUE THREAD

**Issue by MOAMSA** [Blair-Johnson/OMQDI#2]
How can we apply it to other imaging tools instead of MRI? Is there any specific task we can do to tune the algorithm for other imaging or just exploring the result would be enough? Thanks,

**Comment by Blair-Johnson** [comment]
I think you could apply this method to other imaging types. You may need to tune the filters for the wavelet decomposition. You can read more about the rationale for the metric in the linked paper. As with any metric, the results are somewhat subjective (despite the name).
